version: "3.8"
services:
  backend:
    build: .
    container_name: prodrank
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - question_data:/app/data

  nginx:
    image: nginx:alpine
    container_name: prodrank-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  question_data:
