version: "3.8"
services:
  backend:
    build: .
    container_name: prodrank
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - shopify_client_id=${SHOPIFY_CLIENT_ID}
      - shopify_client_secret=${SHOPIFY_CLIENT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
    volumes:
      - question_data:/app/data
      - question_tasks:/app/tasks

  nginx:
    image: nginx:alpine
    container_name: prodrank-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert.pem:/etc/nginx/ssl/cert.pem
      - ./key.pem:/etc/nginx/ssl/key.pem
    depends_on:
      - backend

volumes:
  question_data:
  question_tasks:
