import Link from "next/link";

export default function PrivacyPage() {
  return (<><main className="min-h-screen max-w-3xl mx-auto px-4 py-16 space-y-6">
    <Link href="/" className="text-zinc-500 text-sm">← Home</Link><h1 className="text-3xl font-bold">Privacy Policy</h1><p className="text-sm text-zinc-500">Last updated: July 25, 2026</p>
    <div className="space-y-6 text-sm text-zinc-400 leading-relaxed">
      <section><h2 className="text-lg font-semibold text-zinc-200 mb-2">1. Information We Collect</h2><p>We collect: email address (for account creation), store domain and product data (to provide AI analysis), and usage analytics (page views, features used). We do NOT collect payment information — payments are processed by Paddle.</p></section>
      <section><h2 className="text-lg font-semibold text-zinc-200 mb-2">2. How We Use Your Data</h2><p>Your data is used exclusively to: provide AI visibility analysis, generate optimization recommendations, track ranking changes over time, and improve our service. We never sell your data.</p></section>
      <section><h2 className="text-lg font-semibold text-zinc-200 mb-2">3. Data Storage</h2><p>Account data is stored on Supabase (US East). AI content generation is processed via the DeepSeek API. Payment data is handled entirely by Paddle — we never see your credit card.</p></section>
      <section><h2 className="text-lg font-semibold text-zinc-200 mb-2">4. Cookies</h2><p>We use essential cookies for authentication (Supabase Auth) and analytics (Cloudflare). No tracking cookies. No ad cookies.</p></section>
      <section><h2 className="text-lg font-semibold text-zinc-200 mb-2">5. Your Rights</h2><p>You may request deletion of your data at any time by contacting <a href="mailto:support@prodrank.app" className="text-emerald-400">support@prodrank.app</a>. We will comply within 30 days.</p></section>
      <section><h2 className="text-lg font-semibold text-zinc-200 mb-2">6. GDPR Compliance</h2><p>EU users have the right to access, rectify, and erase their personal data. ProdRank acts as a data controller for account information and a data processor for store data analyzed through the Service.</p></section>
      <section><h2 className="text-lg font-semibold text-zinc-200 mb-2">7. Shopify App Data Processing</h2><p>When you install the ProdRank Shopify App, we process: product data (titles, descriptions, prices, images, SKUs), store information (name, email, plan, currency, timezone), and an OAuth access token used solely to read and write product metafields for schema and AI content. We do not process or store customer order data, customer personal information, or payment information. Your access token is used only against your own store's Admin API and is never exposed to third parties.</p></section>
      <section><h2 className="text-lg font-semibold text-zinc-200 mb-2">8. Automated Deletion (GDPR Webhooks)</h2><p>To comply with Shopify's App Store requirements and GDPR, we implement Shopify's mandatory data-privacy webhooks: <code className="bg-zinc-800 px-1 rounded">customers/data_request</code>, <code className="bg-zinc-800 px-1 rounded">customers/redact</code>, and <code className="bg-zinc-800 px-1 rounded">shop/redact</code>. When Shopify triggers <code className="bg-zinc-800 px-1 rounded">shop/redact</code> (a merchant deletes their store or requests erasure), all data associated with that store — products, generated content, usage history, and connection records — is permanently deleted within 24 hours. Because we store no customer data, <code className="bg-zinc-800 px-1 rounded">customers/redact</code> has nothing to purge.</p></section>
      <section><h2 className="text-lg font-semibold text-zinc-200 mb-2">9. Subprocessors</h2><p>We use the following subprocessors: Supabase (database hosting, US East) for all account and store data; DeepSeek API for AI content generation; Resend for transactional email; Paddle for payment processing (we never see your card details); Cloudflare for CDN and DDoS protection. Each subprocessor is bound by data-processing terms. For the current list, contact <a href="mailto:support@prodrank.app" className="text-emerald-400">support@prodrank.app</a>.</p></section>
    </div>
  </main></>);
}
